### ISSUE TITLE
Bug in README?

### ISSUE THREAD

**Issue by lasseebert** [ysbaddaden/prax#119]
I am using prax for the first time. :+1: for this project!

I had a problem getting up and running. It seemed like prax was simply not running after `prax start` (which acually was the case).

Trying with `prax start --foreground` revealed:

```
$ prax start --foreground
/home/pulver/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rack/utils (LoadError)
...
```

I'm using rbenv and dont have rack installed on `2.2.1` because my project uses `2.1.2` (but `2.2.1` is my global rbenv version).

A simple `cd /opt/prax && bundle` did the trick.

Should this be included in the README?

**Comment by ysbaddaden** [comment]
Prax requires the rack gem (whatever the version) to be installed for the ruby version it should run with. This is noted in the README, if I remember correctly, but maybe it's not emphasised enough.

You'll may want to install rack for the system run, and have Prax use that system ruby, or configure rbenv as per the wiki page, so running prax will select the expected ruby version, and thus find the rack gem.

**Comment by ysbaddaden** [comment]
Please note that only rack is required, I took care to avoid external dependencies as much as possible, to ease the installation.

**Comment by lasseebert** [comment]
Ah, now I see what went wrong for me. I did configure rbenv in `.praxconfig` but I put the config file in the application folder, not in my home folder.

Thanks for your answer.
