### ISSUE TITLE
prax not working on ubuntu 12.04

### ISSUE THREAD

**Issue by chemos57** [ysbaddaden/prax#121]
When trying ot install prax on ubuntu 12.04 i got this output
Starting prax server
/opt/prax/prax/lib/prax/command.rb:12: syntax error, unexpected ':', expecting ')'
Prax.run(daemon: !foreground)

**Comment by ysbaddaden** [comment]
Prax requires Ruby 1.9+. Most likely you are trying to use Ruby 1.8, which isn't supported.

**Comment by chemos57** [comment]
You're totally right! Thanks for help!
