### ISSUE TITLE
prax with systemd, again.

### ISSUE THREAD

**Issue by powder** [ysbaddaden/prax#122]
I am aware of the issue at https://github.com/ysbaddaden/prax/issues/45 , however, I was wondering if prax has ever had an update to address this issue as more and more linux distributions are beginning to use systemd.  Even Ubuntu has made the switch now.  So, while I was abandoning archlinux solely because I can not get prax to work on it, I discovered my next choice in system I know how to use, is also unusable with prax.   Is prax just super deprecated now with a lot of the popular distros switching to systemd?   Is there an alternate tool that does work?

**Comment by ysbaddaden** [comment]
There is nothing that prevents prax to use Prax with systemd.

Prax merely provides a sysvinit script to run at boot time to redirect the 80 and 443 ports to 20559 and 20558 using iptables rules. AFAIK systemd should be capable to run sysvinit scripts. If not, then please create whatever systemd needs to run the iptables rules.

**Comment by powder** [comment]
I apologize for my lack of .. well, because I'm dumb at wording.  What I meant to say, is following instructions I've found (specifically for archlinux) I could not make prax work with systemd.  While there may be ways to coerce it, I'm not figuring it out.  I'd love some more help on getting this to work though.  I am still curious if there's any plans to make it easier, if anyone has anything easier.  Unusable is a strong word and is obviously incorrect. :-1: to myself to that.

I will dive back in and start looking again and see if I can fix it up, this is just a cry for help.

**Comment by ysbaddaden** [comment]
Yes, don't follow the arch/systemd thread. It's meant to start and stop prax itself as a systemd service, which prax isn't: it's just an app that runs as the current user.

I start it when I log in, using a `~/.config/autostart/prax.desktop` file.
