### ISSUE TITLE
Prax troubleshooting

### ISSUE THREAD

**Issue by ybart** [ysbaddaden/prax#127]
prax is awesome when it works but can be quite troublesome to setup when everything does not work as expected.

I run into the following issue, but I found troubleshooting quite hard.

I wanted to stop every instance of my app, and to be sure I used `prax uninstall` to do this.
- I then reinstalled prax using instructions provided in README but it didn't work.
- I succesfully started my app with `rails s`.
- I still had my `.praxconfig` so the issue should not be with RVM.
- However `curl myapp.dev` resulted in `curl: (52) Empty reply from server`.
- I checked the firewall rules with `service prax status` and everything was in order.
- I then tried to start prax manually using `opt/prax/bin/prax start -f`. This was failing indicating Address already in use - bind(2) for nil port 20559 (Errno::EADDRINUSE).
- I used `netstat -tulpn | grep 20559` to find the offender and killed it. I was then able to start prax successfully.

As you can see, there are many potential point of failure and these might be hard to find.

I would like prax to start logging earlier, especially when it can't start. It would have been useful to find that bind failed early just by checking ~/.prax/logs. I would also be happy with `prax start` displaying information on startup beside the following :

```
RVM loading: /home/ybart/.rvm/environments/ruby-2.2.2`
Starting prax in the background.`
```

It could be either the startup log we can see using `opt/prax/bin/prax start -f` or a message indicating that logs are available in `~/.prax/_logs/prax.log` and `~/.prax/_logs/myapp.log`.

In the meantime, I could create a Troubleshooting Wiki page that would be referenced in the README listing the issues I identified.

What do you think ? Does it seems like a good idea ?

**Comment by ysbaddaden** [comment]
I'm sorry that Prax is so unfriendly when it breaks —and it easily breaks under many conditions, most generally related to version managers —I wish the ruby community would get rid of them.

Prax was merely a toy project for my own use. It attracted a lot of users, yet I never ironed out "details" like debug and troubleshooting. My bad. If you want to contribute either on the wiki or the code, please do, this will be very welcomed by everyone, and me first!

**Comment by ybart** [comment]
It's very nice ttah you contributed this project to the community. I just would like to contribute a Wiki and a PR with a simple README edit to the Wiki at the moment.

**Comment by ysbaddaden** [comment]
Also, I've been working on a [Crystal port of Prax](https://github.com/ysbaddaden/prax.cr) for some months now, which I use daily (I don't use the Ruby version anymore), where I'm trying to address the troubleshooting parts with wiki documentation and better logging.

I'll eventually release DEB/RPM packages that should just work —except for the version managers, unless I decide to add support for them when they are installed in standard locations.
