### ISSUE TITLE
Issue installing prax: Cannot open input file server.csr, No such file or directory

### ISSUE THREAD

**Issue by bbtdev** [ysbaddaden/prax#141]
Hello,
Never used prax before, I would like to give it a try:
./bin/prax install
Installing NSSwitch extension (to resolve .dev domains)
make: 'libnss_prax.so.2' is up to date.
ln -sf /opt/prax/ext/libnss_prax.so.2 /lib
Installing Prax firewall rules
Creating ~/.prax directory
Symlinking prax into /usr/local/bin
Generating SSL key and certificate
problems making Certificate Request
139886252114368:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:../crypto/asn1/a_mbstr.c:102:minsize=2
x509: Cannot open input file server.csr, No such file or directory
x509: Use -help for summary.

**Comment by ysbaddaden** [comment]
The ruby version of prax is no longer maintained. See https://github.com/ysbaddaden/prax.cr instead

**Comment by bbtdev** [comment]
Thank you for the reply!
