### ISSUE TITLE
Not working with Google Chrome

### ISSUE THREAD

**Issue by maxbortone** [ysbaddaden/prax#51]
I've just installed Prax under Ubuntu 13.04. I've noticed that I can't reach myapp.dev under Google Chrome, but it works with Firefox. How is this possible?

**Comment by RajRoR** [comment]
This was working for me, however, suddenly it stopped working on Chrome version 39.0.2171.95 (64-bit), ubuntu.

Now it shows default apache page

**Comment by ysbaddaden** [comment]
I'm afraid I have no idea what's happening. Is `libnss_prax.so.2` still in `/lib`?

**Comment by RajRoR** [comment]
I don't think so. Here is the contents of `/lib' http://gyazo.com/9f7db5eaa8ccf18fd0e233e48a3c618d

**Comment by ysbaddaden** [comment]
I meant the system `/lib` not `prax/lib`

**Comment by RajRoR** [comment]
Sorry, my bad. Yes, I have `/lib/libnss_prax.so.2`

**Comment by ysbaddaden** [comment]
It must Chrome's asynchronous DNS then. I had to disable it for Chromium 39.0.2171.65 to work.

**Comment by RajRoR** [comment]
:+1: thanks man!, it worked!

**Comment by mshappe** [comment]
Ubuntu 15.04, Chromium 41 none of these suggestions work.
